(function(){var __webpack_modules__={"./src/js/Chunk/contacts__mail.js":
/*!****************************************!*\
  !*** ./src/js/Chunk/contacts__mail.js ***!
  \****************************************/function(){eval('$(document).ready(function () {\r\n\r\n    //E-mail Ajax Send\r\n    $(".contact__form").submit(function () { //Change\r\n        var th = $(this);\r\n        $.ajax({\r\n            type: "POST",\r\n            url: "php/mail.php", //Change\r\n            data: th.serialize()\r\n        }).done(function () {\r\n            alert("Thank you!");\r\n            setTimeout(function () {\r\n                // Done Functions\r\n                th.trigger("reset");\r\n            }, 1000);\r\n        });\r\n        return false;\r\n    });\r\n\r\n});\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/contacts__mail.js?')},"./src/js/Chunk/findhotel.js":
/*!***********************************!*\
  !*** ./src/js/Chunk/findhotel.js ***!
  \***********************************/function(){eval("const dropdownButton = document.querySelector('.findhotell__dropdown-botton')\r\nconst dropdownList = document.querySelector('.findhotell__dropdown-list')\r\nconst dropdownListItem = document.querySelectorAll('.findhotell__dropdown-list-item')\r\nconst dropdownInput = document.querySelector('.findhotell__dropdown-input')\r\n\r\n\r\ndropdownButton.addEventListener(\"click\", (e) => {\r\n    e.stopPropagation()\r\n    dropdownList.classList.toggle('findhotell__dropdown-list-visible')\r\n\r\n})\r\n\r\n//ВЫБОР ЭЛЕМЕНТА СПИСКА. ЗАПОМНИТЬ ЗНАЧЕНИЕ. ЗАКРЫТЬ ДРОПДАУН\r\ndropdownListItem.forEach(function (listItem) {\r\n    listItem.addEventListener(\"click\", (e) => {\r\n        e.stopPropagation()\r\n        dropdownButton.innerText = listItem.innerText\r\n        dropdownList.classList.remove('findhotell__dropdown-list-visible')\r\n        dropdownInput.value = listItem.dataset.value\r\n    })\r\n})\r\n\r\n\r\n//КЛИК СНАРУЖИ ДРОПДАУНА. ЗАКРЫТЬ ДРОПДАУН\r\ndocument.addEventListener('click', function (e) {\r\n\r\n    dropdownList.classList.remove('findhotell__dropdown-list-visible')\r\n    if (e.target !== dropdownButton) {\r\n        dropdownList.classList.remove('findhotell__dropdown-list-visible')\r\n\r\n    }\r\n\r\n})\r\n\r\n\r\n//Нажатие на tab или escape. Закрыть дропдаун\r\ndocument.addEventListener('keydown', function (e) {\r\n    if (e.key === 'Tab' || e.key === 'Escape') {\r\n        dropdownList.classList.remove('findhotell__dropdown-list-visible')\r\n    }\r\n})\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/findhotel.js?")},"./src/js/Chunk/goto.js":
/*!******************************!*\
  !*** ./src/js/Chunk/goto.js ***!
  \******************************/function(){eval("const menuLinks = document.querySelectorAll('[data-goto]')\r\nconsole.log(menuLinks)\r\nif (menuLinks.length > 0) {\r\n    menuLinks.forEach(menuLink => {\r\n        menuLink.addEventListener('click', onMenuLinkClick)\r\n    })\r\n\r\n    function onMenuLinkClick(e) {\r\n        const menuLink = e.target;\r\n        if (menuLink.dataset.goto && document.querySelector(menuLink.dataset.goto)) {\r\n            const gotoBlock = document.querySelector(menuLink.dataset.goto)\r\n            const gotoBlockValue = gotoBlock.getBoundingClientRect().top + pageYOffset - document.querySelector('.header').offsetHeight;\r\n\r\n            if (document.documentElement.clientWidth <= 426) {\r\n                window.scrollTo({\r\n                    top: gotoBlockValue - 180,\r\n                    behavior: \"smooth\"\r\n                });\r\n            } else {\r\n                window.scrollTo({\r\n                    top: gotoBlockValue,\r\n                    behavior: \"smooth\"\r\n                });\r\n            }\r\n            //header.classList.remove('_active');\r\n            //menuBody.classList.remove('_active')\r\n            //document.body.classList.remove('_active')\r\n            //homepageBody.classList.remove('_active')\r\n            //e.preventDefault();\r\n        }\r\n    }\r\n}\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/goto.js?")},"./src/js/Chunk/location__tabs.js":
/*!****************************************!*\
  !*** ./src/js/Chunk/location__tabs.js ***!
  \****************************************/function(){eval("const tabsBtn = document.querySelectorAll('.tabs__location-button');\r\nconst tabsItems = document.querySelectorAll('.location__item')\r\n\r\n\r\ntabsBtn.forEach(function (item) {\r\n    item.addEventListener(\"click\", function () {\r\n        let currentBtn = item;\r\n        let tabId = currentBtn.getAttribute('data-tab')\r\n        let currentTab = document.querySelector(tabId)\r\n\r\n        if (!currentBtn.classList.contains('active')) {\r\n            tabsBtn.forEach(function (item) {\r\n                item.classList.remove('active')\r\n            })\r\n            tabsItems.forEach(function (item) {\r\n                item.classList.remove('active')\r\n            })\r\n        }\r\n\r\n\r\n\r\n        currentBtn.classList.add('active')\r\n        currentTab.classList.add('active')\r\n    })\r\n})\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/location__tabs.js?")},"./src/js/Chunk/popupTab.js":
/*!**********************************!*\
  !*** ./src/js/Chunk/popupTab.js ***!
  \**********************************/function(){eval("const tabsBtn = document.querySelectorAll('.popup__tabs-buttons')\r\nconst tabsItems = document.querySelectorAll('.popups__item')\r\nconst popupContent = document.querySelector('.header__popup-content')\r\nconst popupBody = document.querySelector('.popup__body')\r\n\r\n\r\n\r\ntabsBtn.forEach(function (item) {\r\n    item.addEventListener(\"click\", function () {\r\n        let currentBtn = item;\r\n        let tabId = currentBtn.getAttribute('data-tab')\r\n        let currentTab = document.querySelector(tabId)\r\n\r\n        if (!currentBtn.classList.contains('active')) {\r\n            tabsBtn.forEach(function (item) {\r\n                item.classList.remove('active')\r\n            })\r\n            tabsItems.forEach(function (item) {\r\n                item.classList.remove('active')\r\n            })\r\n        }\r\n\r\n\r\n\r\n        currentBtn.classList.add('active')\r\n        currentTab.classList.add('active')\r\n    })\r\n})\r\n\r\n\r\nconst headerBtn = document.querySelector('#header__button')\r\nlet popupId = headerBtn.getAttribute('data-popup')\r\nlet openPopup = document.querySelector(popupId)\r\n\r\nheaderBtn.addEventListener('click', function () {\r\n    let popupId = headerBtn.getAttribute('data-popup')\r\n    let openPopup = document.querySelector(popupId)\r\n    openPopup.classList.add('open')\r\n    popupContent.classList.add('open')\r\n    document.body.classList.add('open')\r\n    if (openPopup.classList.contains('open')) {\r\n        const closePopup = document.querySelector('.close')\r\n        document.addEventListener('keydown', function (e) {\r\n            if (e.key === 'Tab' || e.key === 'Escape') {\r\n                openPopup.classList.remove('open')\r\n                popupContent.classList.remove('open')\r\n                document.body.classList.remove('open')\r\n            }\r\n        })\r\n        closePopup.addEventListener('click', () => {\r\n            openPopup.classList.remove('open')\r\n            popupContent.classList.remove('open')\r\n            document.body.classList.remove('open')\r\n        })\r\n    }\r\n})\r\n\r\ndocument.addEventListener('click', function (e) {\r\n    console.log(e.target)\r\n\r\n    if ((e.target === popupBody) && (e.target !== headerBtn)) {\r\n        openPopup.classList.remove('open')\r\n        popupContent.classList.remove('open')\r\n        document.body.classList.remove('open')\r\n\r\n    }\r\n\r\n})\r\n\r\n\r\n\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/popupTab.js?")},"./src/js/Chunk/scrollAnim.js":
/*!************************************!*\
  !*** ./src/js/Chunk/scrollAnim.js ***!
  \************************************/function(){eval("const animItems = document.querySelectorAll('.anim-items') // ДОБАВИТЬ КЛАСС anim-items к анимируемому объекту\r\nif (animItems.length > 0) {\r\n    window.addEventListener('scroll', animOnScroll)\r\n    function animOnScroll() {\r\n        for (let index = 0; index < animItems.length; index++) {\r\n            const animItem = animItems[index]\r\n            const animItemHeight = animItem.offsetHeight\r\n            const animItemOffset = offset(animItem).top\r\n            const animStart = 4\r\n\r\n            let animItemPoint = window.innerHeight - animItemHeight / animStart\r\n            if (animItemHeight > window.innerHeight) {\r\n                animItemPoint = window.innerHeight - window.innerHeight / animStart\r\n            }\r\n\r\n            if ((pageYOffset > animItemOffset - animItemPoint) && pageYOffset < (animItemOffset + animItemHeight)) {\r\n                animItem.classList.add('anim-active')\r\n            } else {\r\n                animItem.classList.remove('anim-active')\r\n            }\r\n        }\r\n\r\n\r\n    }\r\n    function offset(el) {\r\n        const rect = el.getBoundingClientRect(),\r\n            scrollLeft = window.pageXOffset || document.documentElement.scrollLeft,\r\n            scrollTop = window.pageYOffset || document.documentElement.scrollTop\r\n        return { top: rect.top + scrollTop, left: rect.left + screenLeft }\r\n    }\r\n\r\n    setTimeout(() => {\r\n        animOnScroll()\r\n    }, 300);\r\n}\n\n//# sourceURL=webpack://gulp-starter/./src/js/Chunk/scrollAnim.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/function(){eval("\n\n//# sourceURL=webpack://gulp-starter/./src/js/main.js?")}};__webpack_modules__["./src/js/main.js"](),__webpack_modules__["./src/js/Chunk/contacts__mail.js"](),__webpack_modules__["./src/js/Chunk/findhotel.js"](),__webpack_modules__["./src/js/Chunk/goto.js"](),__webpack_modules__["./src/js/Chunk/location__tabs.js"](),__webpack_modules__["./src/js/Chunk/popupTab.js"]();var __webpack_exports__={};__webpack_modules__["./src/js/Chunk/scrollAnim.js"]()})();